#!/usr/bin/env bash
# Submit an Android build to Google Play via EAS using Workload Identity
# Federation (WIF) — no JSON service account key required.
#
# Usage (run from artifacts/knowyourpit/):
#   ./scripts/submit-android.sh                    # submits the latest finished build
#   ./scripts/submit-android.sh <EAS_BUILD_ID>     # submits a specific build by ID
#
# Required secret (set in Replit Secrets):
#   GOOGLE_PLAY_WIF_CONFIG — contents of the WIF credential config JSON
#                            generated by scripts/setup-wif.sh
#                            (external_account type, no private key).
#
# How WIF works (no JSON key needed):
#   EAS Submit obtains a short-lived OIDC token from https://oidc.expo.dev,
#   writes it to /tmp/expo_oidc_subject_token, then the Google auth library
#   exchanges it for a GCP access token via the STS endpoint configured in
#   the credential config.  The credential config tells the auth library which
#   WIF pool/provider to use and which service account to impersonate.
#
# One-time GCP setup: run scripts/setup-wif.sh and follow its printed steps.

set -euo pipefail

WIF_CONFIG_FILE="/tmp/google-play-wif-config.json"

python3 - "$WIF_CONFIG_FILE" <<'EOF'
import os, sys, json

config_file = sys.argv[1]

content = os.environ.get("GOOGLE_PLAY_WIF_CONFIG", "")

if not content:
    print("ERROR: GOOGLE_PLAY_WIF_CONFIG secret is not set", file=sys.stderr)
    print("", file=sys.stderr)
    print("Run scripts/setup-wif.sh to generate the credential config, then", file=sys.stderr)
    print("store its output in a Replit secret named GOOGLE_PLAY_WIF_CONFIG.", file=sys.stderr)
    sys.exit(1)

try:
    parsed = json.loads(content)
    cred_type = parsed.get("type", "")
    if cred_type == "service_account":
        print("ERROR: GOOGLE_PLAY_WIF_CONFIG looks like an old service account JSON key.", file=sys.stderr)
        print("       This script now uses Workload Identity Federation (external_account).", file=sys.stderr)
        print("       Run scripts/setup-wif.sh to generate a WIF credential config.", file=sys.stderr)
        sys.exit(1)
    if cred_type != "external_account":
        print(f"ERROR: GOOGLE_PLAY_WIF_CONFIG has unexpected type '{cred_type}' (expected 'external_account')", file=sys.stderr)
        sys.exit(1)
except json.JSONDecodeError as e:
    print(f"ERROR: GOOGLE_PLAY_WIF_CONFIG is not valid JSON: {e}", file=sys.stderr)
    sys.exit(1)

with open(config_file, "w") as f:
    f.write(content)

print(f"WIF credential config written to {config_file}")
EOF

BUILD_ARG=""
if [ -n "${1:-}" ]; then
    BUILD_ARG="--id $1"
    echo "Submitting build $1 ..."
else
    echo "Submitting latest finished build ..."
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
EAS_BIN="${SCRIPT_DIR}/../node_modules/.bin/eas"
if [ ! -x "$EAS_BIN" ]; then
    EAS_BIN="npx eas"
fi

EXPO_NO_TELEMETRY=1 $EAS_BIN submit \
    --platform android \
    --profile production \
    --android-service-account-key-path "$WIF_CONFIG_FILE" \
    $BUILD_ARG \
    --non-interactive

echo ""
echo "✅ EAS Android submission complete."
