import { StyleSheet } from "react-native";

export const planStyles = StyleSheet.create({
  container: { flex: 1 },
  label: { fontSize: 13, fontFamily: "Inter_600SemiBold", marginBottom: 8, marginTop: 16 },

  inputWrap: {
    borderWidth: 1,
    paddingHorizontal: 14,
    marginBottom: 0,
    flexDirection: "row",
    alignItems: "center",
  },
  input: { flex: 1, height: 48, fontSize: 15, fontFamily: "Inter_400Regular" },
  inputUnit: { fontSize: 13, fontFamily: "Inter_500Medium", marginLeft: 4 },

  tempRow: { flexDirection: "row", alignItems: "flex-start" },

  dropdown: {
    borderWidth: 1,
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    minHeight: 52,
  },
  dropdownValue: { fontSize: 15, fontFamily: "Inter_600SemiBold" },
  dropdownSub: { fontSize: 12, fontFamily: "Inter_400Regular", marginTop: 2 },
  dropdownPlaceholder: { fontSize: 15, fontFamily: "Inter_400Regular" },

  grillChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  chipText: { fontSize: 13, fontFamily: "Inter_500Medium" },
  grillChipText: { fontSize: 13, fontFamily: "Inter_500Medium" },

  grillStatsCard: {
    borderWidth: 1,
    marginBottom: 4,
    overflow: "hidden",
  },
  grillStatsHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 12,
    paddingBottom: 8,
  },
  grillStatIcon: {
    width: 28,
    height: 28,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  grillStatsTitle: { fontSize: 14, fontFamily: "Inter_600SemiBold" },
  grillStatsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    padding: 8,
    gap: 0,
  },
  statCell: {
    width: "50%",
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  statLabel: { fontSize: 11, fontFamily: "Inter_500Medium", marginBottom: 2 },
  statValue: { fontSize: 13, fontFamily: "Inter_600SemiBold" },
  tempWarning: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    margin: 10,
    marginTop: 0,
    padding: 10,
    borderRadius: 8,
  },
  tempWarningText: { flex: 1, fontSize: 12, fontFamily: "Inter_400Regular", color: "#ef4444" },

  serveByCard: {
    borderWidth: 1,
    overflow: "hidden",
  },
  serveByRow: {
    flexDirection: "row",
    alignItems: "center",
    padding: 14,
    gap: 10,
  },
  serveByLabel: { flex: 1, fontSize: 14, fontFamily: "Inter_500Medium" },
  serveByDivider: { height: 1, marginHorizontal: 14 },
  serveByBtn: { paddingHorizontal: 12, paddingVertical: 6 },
  serveByBtnText: { fontSize: 14, fontFamily: "Inter_600SemiBold" },

  scheduleCard: { borderWidth: 1, overflow: "hidden", marginTop: 16 },
  scheduleHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  scheduleHeaderText: { fontSize: 14, fontFamily: "Inter_700Bold", color: "#fff" },
  scheduleBody: { paddingHorizontal: 14, paddingVertical: 8 },
  scheduleLine: { height: 1, marginLeft: 40, marginVertical: 4 },
  scheduleRow: { flexDirection: "row", alignItems: "flex-start", gap: 12, paddingVertical: 8 },
  scheduleIcon: {
    width: 28,
    height: 28,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 2,
  },
  scheduleLabel: { fontSize: 11, fontFamily: "Inter_500Medium", marginBottom: 1 },
  scheduleValue: { fontSize: 14, fontFamily: "Inter_600SemiBold" },
  scheduleSub: { fontSize: 11, fontFamily: "Inter_400Regular", marginTop: 1 },
  scheduleTip: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    margin: 12,
    marginTop: 0,
    padding: 10,
    borderRadius: 8,
  },
  scheduleTipText: { flex: 1, fontSize: 12, fontFamily: "Inter_400Regular", fontStyle: "italic" },

  submitBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    height: 52,
    marginTop: 20,
  },
  submitText: { fontSize: 16, fontFamily: "Inter_600SemiBold", color: "#fff" },

  // AI button
  aiBtn: { marginTop: 20, overflow: "hidden" },
  aiBtnGradient: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  aiBtnText: { fontSize: 15, fontFamily: "Inter_700Bold", color: "#fff" },
  aiBtnSub: { fontSize: 12, fontFamily: "Inter_400Regular", color: "rgba(255,255,255,0.75)", marginTop: 2 },
  aiAppliedBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    padding: 10,
    borderWidth: 1,
    marginTop: 8,
  },
  aiAppliedText: { fontSize: 13, fontFamily: "Inter_500Medium", flex: 1 },

  // AI modal
  aiModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 18,
    paddingVertical: 16,
  },
  aiModalTitle: { fontSize: 18, fontFamily: "Inter_700Bold", color: "#fff" },
  aiModalSub: { fontSize: 12, fontFamily: "Inter_400Regular", color: "rgba(255,255,255,0.8)", marginTop: 2 },
  aiSection: {
    borderBottomWidth: 1,
    paddingVertical: 14,
  },
  aiSectionTitle: { fontSize: 13, fontFamily: "Inter_700Bold", marginBottom: 8, textTransform: "uppercase", letterSpacing: 0.5 },
  aiBody: { fontSize: 14, fontFamily: "Inter_400Regular", lineHeight: 21 },
  aiScheduleRow: { flexDirection: "row", alignItems: "flex-start", gap: 12, paddingVertical: 6 },
  aiScheduleLabel: { fontSize: 11, fontFamily: "Inter_500Medium", marginBottom: 1 },
  aiScheduleVal: { fontSize: 14, fontFamily: "Inter_600SemiBold" },
  wrapBadgeRow: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  wrapBadge: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 20 },
  wrapBadgeText: { fontSize: 12, fontFamily: "Inter_600SemiBold" },
  restRow: { flexDirection: "row", alignItems: "center", gap: 8, padding: 10, marginTop: 10 },
  restText: { fontSize: 13, fontFamily: "Inter_500Medium" },
  tipRow: { flexDirection: "row", alignItems: "flex-start", gap: 10, paddingVertical: 4 },
  tipBullet: { width: 6, height: 6, borderRadius: 3, marginTop: 7 },
  tipText: { flex: 1, fontSize: 14, fontFamily: "Inter_400Regular", lineHeight: 20 },
  applyBtn: { overflow: "hidden", marginTop: 20 },
  applyBtnGradient: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    paddingVertical: 14,
  },
  applyBtnText: { fontSize: 16, fontFamily: "Inter_700Bold", color: "#fff" },
  dismissBtn: {
    alignItems: "center",
    paddingVertical: 12,
    marginTop: 10,
    borderWidth: 1,
  },
  dismissBtnText: { fontSize: 14, fontFamily: "Inter_500Medium" },

  // Modals
  modalOverlay: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  modalSheet: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    minHeight: "65%",
    maxHeight: "85%",
  },
  modalSheetSm: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: "65%",
  },
  modalHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    alignSelf: "center",
    marginTop: 10,
    marginBottom: 4,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderBottomWidth: 1,
  },
  modalTitle: { fontSize: 18, fontFamily: "Inter_700Bold" },

  catTabRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    padding: 14,
    paddingTop: 10,
    gap: 8,
  },
  catTab: { paddingHorizontal: 14, paddingVertical: 7 },
  catTabText: { fontSize: 13, fontFamily: "Inter_600SemiBold" },

  cutRow: { paddingVertical: 12, paddingHorizontal: 4, flexDirection: "row", alignItems: "center" },
  cutSep: { height: 1, marginHorizontal: 4 },
  cutName: { fontSize: 15, fontFamily: "Inter_600SemiBold", marginBottom: 2 },
  cutMeta: { fontSize: 12, fontFamily: "Inter_400Regular" },
  cutNote: { fontSize: 11, fontFamily: "Inter_400Regular", fontStyle: "italic", marginTop: 2 },

  dateRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 10,
    gap: 10,
  },
  dateText: { fontSize: 16, fontFamily: "Inter_600SemiBold", flex: 1 },
  dateSubText: { fontSize: 12, fontFamily: "Inter_400Regular" },

  nowCookingBanner: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 11,
    gap: 8,
  },
  nowCookingLeft: { flex: 1, flexDirection: "row", alignItems: "center", gap: 8 },
  nowCookingDot: { width: 8, height: 8, borderRadius: 4, opacity: 0.9 },
  nowCookingTitle: { flex: 1, fontSize: 14, fontFamily: "Inter_700Bold", color: "#fff" },
  nowCookingElapsed: { fontSize: 13, fontFamily: "Inter_600SemiBold", color: "#fff", opacity: 0.85 },

  // Prep guide
  prepGuideCard: { borderWidth: 1, marginBottom: 12, overflow: "hidden" },
  prepGuideHeader: { flexDirection: "row", alignItems: "center", gap: 10, padding: 14 },
  prepGuideIconWrap: { width: 30, height: 30, borderRadius: 8, alignItems: "center", justifyContent: "center" },
  prepGuideTitle: { fontSize: 14, fontFamily: "Inter_600SemiBold", marginBottom: 1 },
  prepGuidePreview: { fontSize: 12, fontFamily: "Inter_400Regular" },
  prepGuideBody: { paddingHorizontal: 14, paddingBottom: 14, gap: 12 },
  prepStep: { flexDirection: "row", gap: 10, alignItems: "flex-start" },
  prepStepNum: { width: 22, height: 22, borderRadius: 11, alignItems: "center", justifyContent: "center", marginTop: 1 },
  prepStepNumText: { fontSize: 11, fontFamily: "Inter_700Bold", color: "#fff" },
  prepStepText: { flex: 1, fontSize: 13, fontFamily: "Inter_400Regular", lineHeight: 20 },
  prepTipCard: { flexDirection: "row", gap: 10, padding: 12, alignItems: "flex-start", marginTop: 4 },
  prepTipText: { flex: 1, fontSize: 13, fontFamily: "Inter_400Regular", lineHeight: 20 },

  // Mode toggle
  modeToggleRow: { flexDirection: "row", padding: 4, gap: 4, borderWidth: 1, marginBottom: 14 },
  modeToggleBtn: { flex: 1, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6, paddingVertical: 9 },
  modeToggleText: { fontSize: 13, fontFamily: "Inter_600SemiBold" },

  // Weather strip
  weatherStrip: { flexDirection: "row", alignItems: "center", gap: 6, borderWidth: 1, borderRadius: 8, paddingHorizontal: 12, paddingVertical: 8, marginBottom: 10 },
  weatherText: { fontSize: 12, fontFamily: "Inter_400Regular" },
  weatherTempText: { fontSize: 12, fontFamily: "Inter_600SemiBold" },

  // Frozen-to-Table
  proPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    backgroundColor: "#A855F7",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
  },
  proPillText: { fontSize: 9, fontFamily: "Inter_700Bold", color: "#fff", letterSpacing: 0.5 },
  toggleTrack: { width: 40, height: 22, borderRadius: 12, borderWidth: 1, padding: 1, justifyContent: "center" },
  toggleThumb: { width: 18, height: 18, borderRadius: 9 },

  // First-action hero (frozen mode)
  firstActionCard: { marginTop: 16, overflow: "hidden" },
  firstActionInner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  firstActionIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.18)",
    alignItems: "center",
    justifyContent: "center",
  },
  firstActionLabel: {
    fontSize: 10,
    fontFamily: "Inter_700Bold",
    color: "rgba(255,255,255,0.85)",
    letterSpacing: 1,
    marginBottom: 2,
  },
  firstActionTitle: { fontSize: 15, fontFamily: "Inter_700Bold", color: "#fff" },
  firstActionSub: { fontSize: 12, fontFamily: "Inter_400Regular", color: "rgba(255,255,255,0.85)", marginTop: 2 },

  frozenWarning: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    backgroundColor: "#F59E0B18",
    borderWidth: 1,
    borderColor: "#F59E0B40",
    padding: 12,
    marginTop: 12,
  },
  frozenWarningTitle: { fontSize: 13, fontFamily: "Inter_700Bold", color: "#F59E0B", marginBottom: 2 },
  frozenWarningBody: { fontSize: 12, fontFamily: "Inter_400Regular", color: "#92400E", lineHeight: 17 },

  // Multi-cook
  multiEmptyBox: { borderWidth: 1, borderRadius: 10, padding: 20, alignItems: "center", gap: 10, marginBottom: 12 },
  multiEmptyText: { fontSize: 13, fontFamily: "Inter_400Regular", textAlign: "center", lineHeight: 20 },
  multiItemsList: { borderWidth: 1, borderRadius: 10, marginBottom: 10, overflow: "hidden" },
  multiItemRow: { flexDirection: "row", alignItems: "center", paddingHorizontal: 14, paddingVertical: 12, gap: 10 },
  multiItemInfo: { flex: 1 },
  multiItemName: { fontSize: 14, fontFamily: "Inter_600SemiBold", marginBottom: 2 },
  multiItemMeta: { fontSize: 12, fontFamily: "Inter_400Regular" },
  multiItemSep: { height: 1 },
  multiItemGrillChip: { flexDirection: "row", alignItems: "center", gap: 4, borderWidth: 1, paddingHorizontal: 9, paddingVertical: 5 },
  multiItemGrillChipText: { fontSize: 11, fontFamily: "Inter_500Medium" },
  multiAddBtn: { borderWidth: 1, borderRadius: 10, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, paddingVertical: 13, marginBottom: 12 },
  multiAddBtnText: { fontSize: 14, fontFamily: "Inter_600SemiBold" },

  /* Ask PitMaster about this plan */
  askPitMasterPlanBtn: {
    marginHorizontal: 20,
    marginBottom: 10,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 11,
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 8,
  },
  askPitMasterPlanText: {
    flex: 1,
    fontSize: 14,
    fontFamily: "Inter_500Medium",
  },
});


export const probeCardStyles = StyleSheet.create({
  probeCard: { borderWidth: 1, padding: 14, marginBottom: 12 },
  probeHeader: { flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 12 },
  probeIconWrap: { width: 32, height: 32, borderRadius: 10, alignItems: "center", justifyContent: "center" },
  probeTitle: { fontSize: 15, fontFamily: "Inter_700Bold" },
  probeSub: { fontSize: 12, fontFamily: "Inter_400Regular", marginTop: 1 },
  probeRow: { flexDirection: "row", alignItems: "center", gap: 10, padding: 12, borderWidth: 1, marginBottom: 8 },
  tempBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 8 },
  selectCircle: { width: 22, height: 22, borderRadius: 11, borderWidth: 1.5, alignItems: "center", justifyContent: "center" },
  linkedBanner: { flexDirection: "row", alignItems: "center", gap: 8, padding: 10, borderWidth: 1, marginTop: 4 },
});
