/**
 * with-watch-app — Expo Config Plugin
 *
 * Adds a watchOS 7+ Watch App target to the Xcode project generated by
 * `expo prebuild` and embeds it in the main iPhone app target so EAS Build
 * produces a single IPA that ships both apps.
 *
 * Target type: watch2_app (com.apple.product-type.application.watchapp2)
 * The SwiftUI @main lifecycle (WKApplication) runs entirely in this single
 * target — no separate WatchKit extension target is required.
 *
 * Steps performed:
 *   1. Copy Swift sources → ios/KnowYourPitWatch/
 *   2. Add "group.com.knowyourpit.app" App Group to main app entitlements
 *   3. Add watch2_app native target + file group + build settings
 *   4. Add "Embed Watch Content" copy-files build phase to the main app target
 *      so the Watch app bundle is packaged inside the iPhone IPA
 *   5. Link WatchConnectivity.framework to the main app target
 *
 * Applied via app.json → "plugins": ["./plugins/with-watch-app"]
 */

import {
  ConfigPlugin,
  withDangerousMod,
  withEntitlementsPlist,
  withXcodeProject,
} from "@expo/config-plugins";
import path from "path";
import fs from "fs";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const APP_GROUP = "group.com.knowyourpit.app";
const WATCH_APP_BUNDLE_ID = "com.knowyourpit.app.watchkitapp";
const WATCH_APP_TARGET = "KnowYourPitWatch";
const SWIFT_SOURCES_DIR = path.join(__dirname, "WatchExtension");

// ---------------------------------------------------------------------------
// Step 1 — Copy Watch Swift sources into ios/<WATCH_APP_TARGET>/
// ---------------------------------------------------------------------------

const withWatchSources: ConfigPlugin = (config) =>
  withDangerousMod(config, [
    "ios",
    async (mod) => {
      const iosDir = mod.modRequest.platformProjectRoot;
      const destRoot = path.join(iosDir, WATCH_APP_TARGET);
      const destViews = path.join(destRoot, "Views");

      fs.mkdirSync(destRoot, { recursive: true });
      fs.mkdirSync(destViews, { recursive: true });

      for (const file of fs.readdirSync(SWIFT_SOURCES_DIR)) {
        if (
          file.endsWith(".swift") ||
          file.endsWith(".plist") ||
          file.endsWith(".entitlements")
        ) {
          fs.copyFileSync(
            path.join(SWIFT_SOURCES_DIR, file),
            path.join(destRoot, file)
          );
        }
      }

      const viewsSrc = path.join(SWIFT_SOURCES_DIR, "Views");
      if (fs.existsSync(viewsSrc)) {
        for (const file of fs.readdirSync(viewsSrc)) {
          if (file.endsWith(".swift")) {
            fs.copyFileSync(
              path.join(viewsSrc, file),
              path.join(destViews, file)
            );
          }
        }
      }

      return mod;
    },
  ]);

// ---------------------------------------------------------------------------
// Step 2 — Add App Group entitlement to the main iOS app
// ---------------------------------------------------------------------------

const withAppGroupEntitlement: ConfigPlugin = (config) =>
  withEntitlementsPlist(config, (mod) => {
    const existing: string[] =
      (mod.modResults["com.apple.security.application-groups"] as string[]) ?? [];
    if (!existing.includes(APP_GROUP)) {
      mod.modResults["com.apple.security.application-groups"] = [
        ...existing,
        APP_GROUP,
      ];
    }
    return mod;
  });

// ---------------------------------------------------------------------------
// Step 3 — Add Watch App target, its file group, build settings, and the
// "Embed Watch Content" build phase on the main app target
// ---------------------------------------------------------------------------

const withWatchTarget: ConfigPlugin = (config) =>
  withXcodeProject(config, (mod) => {
    const project = mod.modResults;
    const iosDir = mod.modRequest.platformProjectRoot;

    // Guard: idempotent across multiple prebuild runs
    const nativeTargets = project.pbxNativeTargetSection();
    const alreadyAdded = Object.values(nativeTargets).some(
      (t: unknown) =>
        t !== null &&
        typeof t === "object" &&
        (t as Record<string, unknown>).name === WATCH_APP_TARGET
    );
    if (alreadyAdded) return mod;

    const destRoot = path.join(iosDir, WATCH_APP_TARGET);
    const destViews = path.join(destRoot, "Views");

    // Collect Swift source file paths relative to the ios/ project root
    const sourceFiles: string[] = [];
    if (fs.existsSync(destRoot)) {
      for (const f of fs.readdirSync(destRoot)) {
        if (f.endsWith(".swift")) {
          sourceFiles.push(`${WATCH_APP_TARGET}/${f}`);
        }
      }
    }
    if (fs.existsSync(destViews)) {
      for (const f of fs.readdirSync(destViews)) {
        if (f.endsWith(".swift")) {
          sourceFiles.push(`${WATCH_APP_TARGET}/Views/${f}`);
        }
      }
    }

    // Add file group in the Xcode navigator
    project.addPbxGroup(sourceFiles, WATCH_APP_TARGET, WATCH_APP_TARGET);

    // Add Watch App native target
    // "watch2_app" → product type com.apple.product-type.application.watchapp2
    const addedTarget = project.addTarget(
      WATCH_APP_TARGET,
      "watch2_app",
      WATCH_APP_TARGET,
      WATCH_APP_BUNDLE_ID
    );

    // Explicitly add each Swift source file to the Watch App target so that
    // Xcode compiles them as part of the Watch App (addTarget alone does not
    // wire sources into compile-sources build phase).
    if (addedTarget?.uuid) {
      for (const srcPath of sourceFiles) {
        try {
          project.addSourceFile(srcPath, { target: addedTarget.uuid });
        } catch {
          // Skip duplicates — file may already be registered in project
        }
      }
      // Wire Info.plist as a resources file for the Watch App target
      const plistPath = `${WATCH_APP_TARGET}/Info.plist`;
      try {
        project.addResourceFile(plistPath, { target: addedTarget.uuid });
      } catch {
        // Ignore if already registered
      }
    }

    // Apply watchOS-specific build settings to all configs for this bundle ID
    const buildConfigs = project.pbxXCBuildConfigurationSection();
    for (const key of Object.keys(buildConfigs)) {
      const cfg = buildConfigs[key];
      if (
        cfg !== null &&
        typeof cfg === "object" &&
        "buildSettings" in cfg &&
        (cfg as Record<string, unknown>).buildSettings !== null &&
        typeof (cfg as Record<string, unknown>).buildSettings === "object" &&
        ((cfg as Record<string, Record<string, unknown>>).buildSettings)
          .PRODUCT_BUNDLE_IDENTIFIER === WATCH_APP_BUNDLE_ID
      ) {
        Object.assign(
          (cfg as Record<string, Record<string, unknown>>).buildSettings,
          {
            SWIFT_VERSION: "5.0",
            WATCHOS_DEPLOYMENT_TARGET: "7.0",
            TARGETED_DEVICE_FAMILY: "4",
            APPLICATION_EXTENSION_API_ONLY: "NO",
            CODE_SIGN_STYLE: "Automatic",
            DEVELOPMENT_TEAM: "$(DEVELOPMENT_TEAM)",
            PRODUCT_NAME: "KnowYourPit Watch",
            ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon",
            CODE_SIGN_ENTITLEMENTS: `${WATCH_APP_TARGET}/WatchExtension.entitlements`,
          }
        );
      }
    }

    // Add "Embed Watch Content" copy-files build phase to the main iPhone app
    // target so the Watch app bundle is packaged inside the IPA.
    // Destination 16 = Watch content ($(CONTENTS_FOLDER_PATH)/Watch)
    const mainTarget = project.getFirstTarget();
    if (mainTarget?.uuid && addedTarget?.uuid) {
      try {
        // Get the Watch App's product file reference
        const watchProductRef = addedTarget.pbxNativeTarget?.productReference;
        if (watchProductRef) {
          project.addBuildPhase(
            [watchProductRef],
            "PBXCopyFilesBuildPhase",
            "Embed Watch Content",
            mainTarget.uuid,
            "watch"
          );
        }
      } catch {
        // If automatic embedding fails, the developer must add the
        // "Embed Watch Content" phase manually in Xcode or via EAS build config
      }
    }

    return mod;
  });

// ---------------------------------------------------------------------------
// Step 4 — Link WatchConnectivity.framework to the main app
// ---------------------------------------------------------------------------

const withWatchConnectivityFramework: ConfigPlugin = (config) =>
  withXcodeProject(config, (mod) => {
    try {
      mod.modResults.addFramework("WatchConnectivity.framework", { weak: false });
    } catch {
      // Already linked
    }
    return mod;
  });

// ---------------------------------------------------------------------------
// Compose
// ---------------------------------------------------------------------------

const withWatchApp: ConfigPlugin = (config) => {
  config = withWatchSources(config);
  config = withAppGroupEntitlement(config);
  config = withWatchTarget(config);
  config = withWatchConnectivityFramework(config);
  return config;
};

export default withWatchApp;
