/**
 * with-watch-app — Expo Config Plugin
 *
 * Adds a modern watchOS 7+ Watch App target (single target, no extension) to
 * the Xcode project generated by `expo prebuild`. Also:
 *   - Copies Swift source files from WatchExtension/ into ios/<WatchAppTarget>/
 *   - Adds App Group entitlement to the main iOS app
 *   - Adds WatchConnectivity.framework to the main app's linked frameworks
 *
 * Target type is `watch2_app` (com.apple.product-type.application.watchapp2).
 * The modern SwiftUI app lifecycle (`@main` + WKApplication) runs entirely
 * inside the Watch App target — no separate extension target is needed.
 *
 * Applied in app.json → "plugins": ["./plugins/with-watch-app"]
 */

import {
  ConfigPlugin,
  withDangerousMod,
  withEntitlementsPlist,
  withXcodeProject,
} from "@expo/config-plugins";
import path from "path";
import fs from "fs";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const APP_GROUP = "group.com.knowyourpit.app";
const WATCH_APP_BUNDLE_ID = "com.knowyourpit.app.watchkitapp";
const WATCH_APP_TARGET = "KnowYourPitWatch";
const SWIFT_SOURCES_DIR = path.join(__dirname, "WatchExtension");

// ---------------------------------------------------------------------------
// Step 1 — Add App Group entitlement to the main iOS app
// ---------------------------------------------------------------------------

const withAppGroupEntitlement: ConfigPlugin = (config) =>
  withEntitlementsPlist(config, (mod) => {
    const existing: string[] =
      (mod.modResults["com.apple.security.application-groups"] as string[]) ?? [];
    if (!existing.includes(APP_GROUP)) {
      mod.modResults["com.apple.security.application-groups"] = [
        ...existing,
        APP_GROUP,
      ];
    }
    return mod;
  });

// ---------------------------------------------------------------------------
// Step 2 — Copy Watch Swift sources into ios/<WATCH_APP_TARGET>/
// ---------------------------------------------------------------------------

const withWatchSources: ConfigPlugin = (config) =>
  withDangerousMod(config, [
    "ios",
    async (mod) => {
      const iosDir = mod.modRequest.platformProjectRoot;
      const destRoot = path.join(iosDir, WATCH_APP_TARGET);
      const destViews = path.join(destRoot, "Views");

      fs.mkdirSync(destRoot, { recursive: true });
      fs.mkdirSync(destViews, { recursive: true });

      // Root-level Swift + plist + entitlements
      for (const file of fs.readdirSync(SWIFT_SOURCES_DIR)) {
        if (
          file.endsWith(".swift") ||
          file.endsWith(".plist") ||
          file.endsWith(".entitlements")
        ) {
          fs.copyFileSync(
            path.join(SWIFT_SOURCES_DIR, file),
            path.join(destRoot, file)
          );
        }
      }

      // Views/
      const viewsSrc = path.join(SWIFT_SOURCES_DIR, "Views");
      if (fs.existsSync(viewsSrc)) {
        for (const file of fs.readdirSync(viewsSrc)) {
          if (file.endsWith(".swift")) {
            fs.copyFileSync(
              path.join(viewsSrc, file),
              path.join(destViews, file)
            );
          }
        }
      }

      return mod;
    },
  ]);

// ---------------------------------------------------------------------------
// Step 3 — Add the Watch App target to the Xcode project (pbxproj)
//
// Uses the xcode npm package (already a transitive dep of @expo/config-plugins)
// to add a "watch2_app" native target, a file group, all Swift source files,
// and the correct build settings for watchOS 7+.
// ---------------------------------------------------------------------------

const withWatchTarget: ConfigPlugin = (config) =>
  withXcodeProject(config, (mod) => {
    const project = mod.modResults;
    const iosDir = mod.modRequest.platformProjectRoot;

    // Guard: skip if target already added (idempotent prebuild runs)
    const nativeTargets = project.pbxNativeTargetSection();
    const alreadyAdded = Object.values(nativeTargets).some(
      (t: unknown) =>
        t !== null &&
        typeof t === "object" &&
        (t as Record<string, unknown>).name === WATCH_APP_TARGET
    );
    if (alreadyAdded) return mod;

    const destRoot = path.join(iosDir, WATCH_APP_TARGET);
    const destViews = path.join(destRoot, "Views");

    // Collect source file paths relative to ios/ root (required by addPbxGroup)
    const sourceFiles: string[] = [];

    if (fs.existsSync(destRoot)) {
      for (const f of fs.readdirSync(destRoot)) {
        if (f.endsWith(".swift")) {
          sourceFiles.push(`${WATCH_APP_TARGET}/${f}`);
        }
      }
    }
    if (fs.existsSync(destViews)) {
      for (const f of fs.readdirSync(destViews)) {
        if (f.endsWith(".swift")) {
          sourceFiles.push(`${WATCH_APP_TARGET}/Views/${f}`);
        }
      }
    }

    // Add file group in Xcode project navigator
    project.addPbxGroup(sourceFiles, WATCH_APP_TARGET, WATCH_APP_TARGET);

    // Add native target — "watch2_app" = com.apple.product-type.application.watchapp2
    project.addTarget(
      WATCH_APP_TARGET,
      "watch2_app",
      WATCH_APP_TARGET,
      WATCH_APP_BUNDLE_ID
    );

    // Apply Watch-specific build settings to every configuration that has
    // our Watch app bundle identifier
    const buildConfigs = project.pbxXCBuildConfigurationSection();
    for (const key of Object.keys(buildConfigs)) {
      const cfg = buildConfigs[key];
      if (
        cfg !== null &&
        typeof cfg === "object" &&
        "buildSettings" in cfg &&
        cfg.buildSettings?.PRODUCT_BUNDLE_IDENTIFIER === WATCH_APP_BUNDLE_ID
      ) {
        Object.assign(cfg.buildSettings, {
          SWIFT_VERSION: "5.0",
          WATCHOS_DEPLOYMENT_TARGET: "7.0",
          TARGETED_DEVICE_FAMILY: "4",
          // Watch App target is not an extension
          APPLICATION_EXTENSION_API_ONLY: "NO",
          CODE_SIGN_STYLE: "Automatic",
          DEVELOPMENT_TEAM: "$(DEVELOPMENT_TEAM)",
          PRODUCT_NAME: "KnowYourPit Watch",
          CODE_SIGN_ENTITLEMENTS: `${WATCH_APP_TARGET}/WatchExtension.entitlements`,
        });
      }
    }

    // Link WatchConnectivity.framework to the Watch target as well
    try {
      project.addFramework("WatchConnectivity.framework", {
        weak: false,
        target: WATCH_APP_TARGET,
      });
    } catch {
      // Framework may already be present or linking handled by WCSession directly
    }

    return mod;
  });

// ---------------------------------------------------------------------------
// Step 4 — Link WatchConnectivity.framework to the main app target
// ---------------------------------------------------------------------------

const withWatchConnectivityFramework: ConfigPlugin = (config) =>
  withXcodeProject(config, (mod) => {
    const project = mod.modResults;
    try {
      project.addFramework("WatchConnectivity.framework", { weak: false });
    } catch {
      // Already linked
    }
    return mod;
  });

// ---------------------------------------------------------------------------
// Compose
// ---------------------------------------------------------------------------

const withWatchApp: ConfigPlugin = (config) => {
  config = withAppGroupEntitlement(config);
  config = withWatchSources(config);
  config = withWatchTarget(config);
  config = withWatchConnectivityFramework(config);
  return config;
};

export default withWatchApp;
