/**
 * with-watch-app — Expo Config Plugin
 *
 * Adds a WatchKit Extension target (KnowYourPit Watch) to the Xcode project
 * generated by `expo prebuild`. It also:
 *   - Copies the Swift Watch extension source files into the build directory
 *   - Adds the "group.com.knowyourpit.app" App Group to the main app entitlements
 *   - Adds the WatchConnectivity local module to the Podfile
 *
 * Applied in app.json → "plugins": ["./plugins/with-watch-app"]
 */

import {
  ConfigPlugin,
  withDangerousMod,
  withEntitlementsPlist,
  withInfoPlist,
  withXcodeProject,
  IOSConfig,
} from "@expo/config-plugins";
import path from "path";
import fs from "fs";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const APP_GROUP = "group.com.knowyourpit.app";
const WATCH_EXT_BUNDLE_ID = "com.knowyourpit.app.watchkitextension";
const WATCH_APP_BUNDLE_ID = "com.knowyourpit.app.watchkitapp";
const WATCH_EXT_TARGET = "KnowYourPitWatchExtension";
const WATCH_APP_TARGET = "KnowYourPitWatch";
const SWIFT_FILES_DIR = path.join(__dirname, "WatchExtension");

// ---------------------------------------------------------------------------
// Step 1 — Add App Group entitlement to the main iOS app
// ---------------------------------------------------------------------------

const withAppGroupEntitlement: ConfigPlugin = (config) =>
  withEntitlementsPlist(config, (mod) => {
    const groups: string[] =
      mod.modResults["com.apple.security.application-groups"] ?? [];
    if (!groups.includes(APP_GROUP)) {
      groups.push(APP_GROUP);
    }
    mod.modResults["com.apple.security.application-groups"] = groups;
    return mod;
  });

// ---------------------------------------------------------------------------
// Step 2 — Copy Watch extension Swift sources into the iOS folder
// ---------------------------------------------------------------------------

const withWatchSources: ConfigPlugin = (config) =>
  withDangerousMod(config, [
    "ios",
    async (mod) => {
      const iosDir = mod.modRequest.platformProjectRoot;

      // Watch extension directory inside the Xcode project folder
      const watchExtDir = path.join(iosDir, WATCH_EXT_TARGET);
      const watchViewsDir = path.join(watchExtDir, "Views");

      fs.mkdirSync(watchExtDir, { recursive: true });
      fs.mkdirSync(watchViewsDir, { recursive: true });

      // Copy root-level Swift files
      const rootFiles = fs.readdirSync(SWIFT_FILES_DIR).filter(
        (f) => f.endsWith(".swift") || f.endsWith(".plist") || f.endsWith(".entitlements")
      );
      for (const file of rootFiles) {
        fs.copyFileSync(
          path.join(SWIFT_FILES_DIR, file),
          path.join(watchExtDir, file)
        );
      }

      // Copy Views/ subdirectory
      const viewsDir = path.join(SWIFT_FILES_DIR, "Views");
      if (fs.existsSync(viewsDir)) {
        for (const file of fs.readdirSync(viewsDir)) {
          if (file.endsWith(".swift")) {
            fs.copyFileSync(
              path.join(viewsDir, file),
              path.join(watchViewsDir, file)
            );
          }
        }
      }

      return mod;
    },
  ]);

// ---------------------------------------------------------------------------
// Step 3 — Add the Watch Extension target to the Xcode project (pbxproj)
// ---------------------------------------------------------------------------

const withWatchTarget: ConfigPlugin = (config) =>
  withXcodeProject(config, (mod) => {
    const project = mod.modResults;

    // Guard against running twice
    const existingTargets = project.pbxNativeTargetSection();
    const alreadyAdded = Object.values(existingTargets).some(
      (t: any) => t && t.name === WATCH_EXT_TARGET
    );
    if (alreadyAdded) return mod;

    const iosDir = mod.modRequest.platformProjectRoot;
    const watchExtDir = path.join(iosDir, WATCH_EXT_TARGET);
    const watchViewsDir = path.join(watchExtDir, "Views");

    // Collect source files for the Watch Extension target
    const swiftFiles: string[] = [
      ...fs.readdirSync(watchExtDir).filter((f) => f.endsWith(".swift")),
    ]
      .map((f) => `${WATCH_EXT_TARGET}/${f}`);

    if (fs.existsSync(watchViewsDir)) {
      const viewFiles = fs
        .readdirSync(watchViewsDir)
        .filter((f) => f.endsWith(".swift"))
        .map((f) => `${WATCH_EXT_TARGET}/Views/${f}`);
      swiftFiles.push(...viewFiles);
    }

    // Use Xcode project's built-in addTargetDependency helper via lower-level API
    // We add the Watch Extension target with its source files and build settings.
    const extTargetKey = project.generateUuid();
    const extTargetGroupKey = project.generateUuid();

    // Add a group for the Watch extension files
    project.addPbxGroup(swiftFiles, WATCH_EXT_TARGET, WATCH_EXT_TARGET);

    // Add the native target
    project.addTarget(WATCH_EXT_TARGET, "watch2_extension", WATCH_EXT_TARGET, WATCH_EXT_BUNDLE_ID);

    // Configure build settings for the extension target
    const target = project.getFirstTarget()?.firstTarget;
    if (target) {
      const configs = project.pbxXCBuildConfigurationSection();
      for (const key of Object.keys(configs)) {
        const cfg = configs[key];
        if (cfg && cfg.buildSettings && cfg.buildSettings.PRODUCT_BUNDLE_IDENTIFIER === WATCH_EXT_BUNDLE_ID) {
          cfg.buildSettings.SWIFT_VERSION = "5.0";
          cfg.buildSettings.WATCHOS_DEPLOYMENT_TARGET = "7.0";
          cfg.buildSettings.TARGETED_DEVICE_FAMILY = "4";
          cfg.buildSettings.APPLICATION_EXTENSION_API_ONLY = "YES";
          cfg.buildSettings.CODE_SIGN_ENTITLEMENTS = `${WATCH_EXT_TARGET}/WatchExtension.entitlements`;
          cfg.buildSettings.APP_GROUP = APP_GROUP;
        }
      }
    }

    return mod;
  });

// ---------------------------------------------------------------------------
// Step 4 — Add the WatchConnectivity module to the Podfile
// ---------------------------------------------------------------------------

const withWatchConnectivityPod: ConfigPlugin = (config) =>
  withDangerousMod(config, [
    "ios",
    async (mod) => {
      const podfilePath = path.join(mod.modRequest.platformProjectRoot, "Podfile");
      if (!fs.existsSync(podfilePath)) return mod;

      let podfile = fs.readFileSync(podfilePath, "utf8");

      const podEntry = `\n  # WatchConnectivity native module\n  pod 'WatchConnectivity', :path => '../modules/watch-connectivity'\n`;

      if (!podfile.includes("WatchConnectivity")) {
        // Insert before the last `end` in the main target block
        podfile = podfile.replace(
          /(\n\s*use_react_native!)/,
          `${podEntry}$1`
        );
        fs.writeFileSync(podfilePath, podfile);
      }

      return mod;
    },
  ]);

// ---------------------------------------------------------------------------
// Step 5 — Add WatchConnectivity framework to the main app's linked frameworks
// ---------------------------------------------------------------------------

const withWatchConnectivityFramework: ConfigPlugin = (config) =>
  withXcodeProject(config, (mod) => {
    const project = mod.modResults;
    try {
      project.addFramework("WatchConnectivity.framework", { weak: false });
    } catch {
      // Already added
    }
    return mod;
  });

// ---------------------------------------------------------------------------
// Compose all sub-plugins
// ---------------------------------------------------------------------------

const withWatchApp: ConfigPlugin = (config) => {
  config = withAppGroupEntitlement(config);
  config = withWatchSources(config);
  config = withWatchTarget(config);
  config = withWatchConnectivityPod(config);
  config = withWatchConnectivityFramework(config);
  return config;
};

export default withWatchApp;
