import { Router, type IRouter } from "express";
import healthRouter from "./health";
import grillsRouter from "./grills";
import cooksRouter from "./cooks";
import recipesRouter from "./recipes";
import temperatureRouter from "./temperature";
import aiRouter from "./ai";
import forumRouter from "./forum";
import tipsRouter from "./tips";
import alertsRouter from "./alerts";
import dashboardRouter from "./dashboard";
import profileRouter from "./profile";
import conversationsRouter from "./conversations";
import meaterRouter from "./meater";
import thermoworksRouter from "./thermoworks";
import contactRouter from "./contact";
import paywallRouter from "./paywall";
import webhooksRouter from "./webhooks";
import customMeatCutsRouter from "./customMeatCuts";
import cookTemplatesRouter from "./cookTemplates";
import adminRouter from "./admin";
import liveActivitiesRouter from "./liveActivities";
import reviewerRouter from "./reviewer";

const router: IRouter = Router();

router.use(healthRouter);
router.use(grillsRouter);
router.use(cooksRouter);
router.use(recipesRouter);
router.use(temperatureRouter);
router.use(aiRouter);
router.use(forumRouter);
router.use(tipsRouter);
router.use(alertsRouter);
router.use(dashboardRouter);
router.use(profileRouter);
router.use(conversationsRouter);
router.use(meaterRouter);
router.use(thermoworksRouter);
router.use(contactRouter);
router.use(paywallRouter);
router.use(webhooksRouter);
router.use(customMeatCutsRouter);
router.use(cookTemplatesRouter);
router.use(adminRouter);
router.use(liveActivitiesRouter);
router.use(reviewerRouter);

export default router;
