const colors = {
  light: {
    text: "#18181c",
    tint: "#EB6C2B",
    background: "#f5f4f2",
    foreground: "#18181c",
    card: "#ffffff",
    cardForeground: "#18181c",
    primary: "#EB6C2B",
    primaryForeground: "#ffffff",
    secondary: "#69513a",
    secondaryForeground: "#ffffff",
    muted: "#e8e4df",
    mutedForeground: "#7a7068",
    accent: "#f0e8e0",
    accentForeground: "#18181c",
    destructive: "#cc4433",
    destructiveForeground: "#ffffff",
    border: "#ddd8d0",
    input: "#ddd8d0",
  },
  dark: {
    text: "#f0ede8",
    tint: "#EB6C2B",
    background: "#18181c",
    foreground: "#f0ede8",
    card: "#1d1d21",
    cardForeground: "#f0ede8",
    primary: "#EB6C2B",
    primaryForeground: "#ffffff",
    secondary: "#69513a",
    secondaryForeground: "#f0ede8",
    muted: "#2a2a31",
    mutedForeground: "#93939f",
    accent: "#2f2f36",
    accentForeground: "#f0ede8",
    destructive: "#cc4433",
    destructiveForeground: "#ffffff",
    border: "#2f2f36",
    input: "#2f2f36",
  },
  radius: 12,
};

export default colors;
