// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/app-store-screenshots/AppStoreExporter.tsx": () => import("../components/mockups/app-store-screenshots/AppStoreExporter.tsx"),
  "./components/mockups/app-store-screenshots/Screen1Dashboard.tsx": () => import("../components/mockups/app-store-screenshots/Screen1Dashboard.tsx"),
  "./components/mockups/app-store-screenshots/Screen2GrillInventory.tsx": () => import("../components/mockups/app-store-screenshots/Screen2GrillInventory.tsx"),
  "./components/mockups/app-store-screenshots/Screen3CookSession.tsx": () => import("../components/mockups/app-store-screenshots/Screen3CookSession.tsx"),
  "./components/mockups/app-store-screenshots/Screen4AIScanner.tsx": () => import("../components/mockups/app-store-screenshots/Screen4AIScanner.tsx"),
  "./components/mockups/app-store-screenshots/Screen5CookPlanner.tsx": () => import("../components/mockups/app-store-screenshots/Screen5CookPlanner.tsx"),
  "./components/mockups/app-store-screenshots/Screen6Recipes.tsx": () => import("../components/mockups/app-store-screenshots/Screen6Recipes.tsx"),
  "./components/mockups/watch-screens/AlertView.tsx": () => import("../components/mockups/watch-screens/AlertView.tsx"),
  "./components/mockups/watch-screens/ComplicationView.tsx": () => import("../components/mockups/watch-screens/ComplicationView.tsx"),
  "./components/mockups/watch-screens/MainCookView.tsx": () => import("../components/mockups/watch-screens/MainCookView.tsx"),
  "./components/mockups/watch-screens/WatchActiveCook.tsx": () => import("../components/mockups/watch-screens/WatchActiveCook.tsx"),
  "./components/mockups/watch-screens/WatchCookControl.tsx": () => import("../components/mockups/watch-screens/WatchCookControl.tsx"),
  "./components/mockups/watch-screens/WatchFuelTimer.tsx": () => import("../components/mockups/watch-screens/WatchFuelTimer.tsx"),
  "./components/mockups/watch-screens/WatchPitMaster.tsx": () => import("../components/mockups/watch-screens/WatchPitMaster.tsx"),
  "./components/mockups/watch-screens/WatchStallAlert.tsx": () => import("../components/mockups/watch-screens/WatchStallAlert.tsx"),
  "./components/mockups/onboarding/Slide1.tsx": () => import("../components/mockups/onboarding/Slide1.tsx"),
  "./components/mockups/onboarding/Slide3.tsx": () => import("../components/mockups/onboarding/Slide3.tsx"),
  "./components/mockups/onboarding/Slide5.tsx": () => import("../components/mockups/onboarding/Slide5.tsx")
};
