// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/watch-screens/AlertView.tsx": () => import("../components/mockups/watch-screens/AlertView.tsx"),
  "./components/mockups/watch-screens/ComplicationView.tsx": () => import("../components/mockups/watch-screens/ComplicationView.tsx"),
  "./components/mockups/watch-screens/MainCookView.tsx": () => import("../components/mockups/watch-screens/MainCookView.tsx")
};
