import { pgTable, text, serial, timestamp, integer, real, jsonb, boolean } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

export const cooksTable = pgTable("cooks", {
  id: serial("id").primaryKey(),
  userId: text("user_id"),
  grillId: integer("grill_id"),
  foodType: text("food_type").notNull(),
  weightLbs: real("weight_lbs"),
  targetTempF: real("target_temp_f"),
  cookTempF: real("cook_temp_f"),
  status: text("status").notNull().default("planned"),
  plannedStartAt: timestamp("planned_start_at", { withTimezone: true }),
  actualStartAt: timestamp("actual_start_at", { withTimezone: true }),
  plannedEndAt: timestamp("planned_end_at", { withTimezone: true }),
  actualEndAt: timestamp("actual_end_at", { withTimezone: true }),
  notes: text("notes"),
  preheatMinutes: integer("preheat_minutes"),
  wrapAtMinutes: integer("wrap_at_minutes"),
  wrapMethod: text("wrap_method"),
  wrapTempF: integer("wrap_temp_f"),
  wrapReason: text("wrap_reason"),
  restMinutes: integer("rest_minutes"),
  ratingTenderness: integer("rating_tenderness"),
  ratingBark: integer("rating_bark"),
  ratingFlavor: integer("rating_flavor"),
  rating: integer("rating"),
  sessionId: text("session_id"),
  sessionLabel: text("session_label"),
  sessionNotes: text("session_notes"),
  sequenceData: jsonb("sequence_data"),
  confirmedSteps: jsonb("confirmed_steps"),
  analysisResult: jsonb("analysis_result"),
  analysisHistory: jsonb("analysis_history"),
  fromFrozen: boolean("from_frozen").notNull().default(false),
  thawMethod: text("thaw_method"),
  actualThawStartAt: timestamp("actual_thaw_start_at", { withTimezone: true }),
  isCompetition: boolean("is_competition").notNull().default(false),
  competitionName: text("competition_name"),
  competitionCategory: text("competition_category"),
  turnInAt: timestamp("turn_in_at", { withTimezone: true }),
  competitionPlacement: integer("competition_placement"),
  competitionTeamCount: integer("competition_team_count"),
  judgeScore: real("judge_score"),
  judgeScoreAppearance: real("judge_score_appearance"),
  judgeScoreTaste: real("judge_score_taste"),
  judgeScoreTexture: real("judge_score_texture"),
  judgeNotes: text("judge_notes"),
  cookingMethod: text("cooking_method"),
  injection: text("injection"),
  spritzFrequency: text("spritz_frequency"),
  spritzLiquid: text("spritz_liquid"),
  wrapFinish: text("wrap_finish"),
  finishTimeRangeLower: timestamp("finish_time_range_lower", { withTimezone: true }),
  finishTimeRangeUpper: timestamp("finish_time_range_upper", { withTimezone: true }),
  healthScore: text("health_score"),
  healthScoreReason: text("health_score_reason"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export const insertCookSchema = createInsertSchema(cooksTable).omit({ id: true, createdAt: true, updatedAt: true });
export type InsertCook = z.infer<typeof insertCookSchema>;
export type Cook = typeof cooksTable.$inferSelect;
