import { StyleSheet } from "react-native";

export const s = StyleSheet.create({
  container: { flex: 1 },
  center: { flex: 1, alignItems: "center", justifyContent: "center" },
  goBackBtn: { marginTop: 16, padding: 12 },

  header: { flexDirection: "row", alignItems: "center", gap: 10, paddingHorizontal: 18, paddingBottom: 16, overflow: "hidden" },
  backBtn: { width: 34, height: 34, alignItems: "center", justifyContent: "center" },
  headerTitle: { flex: 1, fontSize: 20, fontFamily: "Inter_700Bold", color: "#F3EDE1", letterSpacing: -0.3 },
  headerRight: { flexDirection: "row", alignItems: "center", gap: 12 },
  headerLogo: { width: 28, height: 28, opacity: 0.9 },
  delBtn: { padding: 4 },
  fireBar: { height: 2, backgroundColor: "#E84820" },

  statusBar: { flexDirection: "row", alignItems: "center", gap: 10, padding: 14 },
  statusDot: { width: 8, height: 8, borderRadius: 4 },
  statusText: { fontSize: 13, fontFamily: "Inter_700Bold", letterSpacing: 1 },

  card: { borderWidth: 1 },
  row: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", padding: 14 },
  rowLabel: { fontSize: 14, fontFamily: "Inter_500Medium" },
  rowValue: { fontSize: 14, fontFamily: "Inter_400Regular", maxWidth: "55%", textAlign: "right" },
  notesLabel: { fontSize: 12, fontFamily: "Inter_600SemiBold", marginBottom: 6 },
  notesText: { fontSize: 14, fontFamily: "Inter_400Regular", lineHeight: 22 },

  sectionHeaderRow: { flexDirection: "row", alignItems: "center", gap: 8, padding: 12, borderBottomWidth: 1 },
  sectionIconWrap: { width: 24, height: 24, borderRadius: 6, alignItems: "center", justifyContent: "center" },
  sectionHeaderLabel: { fontSize: 12, fontFamily: "Inter_700Bold", textTransform: "uppercase", letterSpacing: 0.8 },

  statTileRow: { flexDirection: "row", borderBottomWidth: 1 },
  statTile: { flex: 1, alignItems: "center", paddingVertical: 16, paddingHorizontal: 8 },
  statTileValue: { fontSize: 18, fontFamily: "Inter_700Bold", marginBottom: 2 },
  statTileLabel: { fontSize: 11, fontFamily: "Inter_500Medium" },

  inlineGradeRow: { flexDirection: "row", alignItems: "center", gap: 12, paddingHorizontal: 14, paddingVertical: 12, borderBottomWidth: 1 },
  inlineGradeBadge: { width: 40, height: 40, borderRadius: 10, borderWidth: 1.5, alignItems: "center", justifyContent: "center" },
  inlineGradeLetter: { fontSize: 20, fontFamily: "Inter_700Bold" },
  inlineGradeTitle: { fontSize: 13, fontFamily: "Inter_700Bold" },
  inlineGradeSub: { fontSize: 12, fontFamily: "Inter_400Regular", marginTop: 1 },
  gradeBarTrackSmall: { height: 5, borderRadius: 3, overflow: "hidden" },

  detailsToggle: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6, borderTopWidth: 1, paddingVertical: 12 },
  detailsToggleText: { fontSize: 13, fontFamily: "Inter_600SemiBold" },

  gradeCard: { borderWidth: 2, flexDirection: "row", alignItems: "center", padding: 16, gap: 16 },
  gradeLeft: { alignItems: "center", minWidth: 52 },
  gradeLetter: { fontSize: 44, fontFamily: "Inter_700Bold", lineHeight: 50 },
  gradeNote: { fontSize: 11, fontFamily: "Inter_500Medium", textAlign: "center", marginTop: 2 },
  gradeRight: { flex: 1, gap: 6 },
  gradeTitle: { fontSize: 13, fontFamily: "Inter_700Bold" },
  gradeBarTrack: { height: 6, borderRadius: 3, overflow: "hidden" },
  gradeBarFill: { height: 6, borderRadius: 3 },
  gradeDeviation: { fontSize: 12, fontFamily: "Inter_400Regular" },

  logSection: { borderWidth: 1, padding: 16, gap: 14 },
  logHeader: { flexDirection: "row", alignItems: "flex-start", gap: 12 },
  logIconWrap: { width: 34, height: 34, borderRadius: 10, alignItems: "center", justifyContent: "center", marginTop: 2 },
  logTitle: { fontSize: 16, fontFamily: "Inter_700Bold" },
  logSub: { fontSize: 12, fontFamily: "Inter_400Regular", lineHeight: 17, marginTop: 3 },

  photoBtns: { flexDirection: "row", gap: 10 },
  photoBtn: { flex: 1, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7, borderWidth: 1, paddingVertical: 10 },
  photoBtnText: { fontSize: 14, fontFamily: "Inter_600SemiBold" },

  thumbRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  thumb: { position: "relative" },
  thumbImg: { width: 72, height: 72, borderRadius: 8 },
  thumbDel: { position: "absolute", top: 3, right: 3, width: 18, height: 18, borderRadius: 9, alignItems: "center", justifyContent: "center" },
  addMoreThumb: { width: 72, height: 72, alignItems: "center", justifyContent: "center", borderWidth: 1, borderStyle: "dashed" },

  notesInputLabel: { fontSize: 12, fontFamily: "Inter_600SemiBold", marginBottom: 6 },
  notesInput: { borderWidth: 1, padding: 12, fontSize: 14, fontFamily: "Inter_400Regular", minHeight: 80 },

  analyzeBtn: { overflow: "hidden" },
  analyzeBtnGradient: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 9, height: 50 },
  analyzeBtnText: { fontSize: 15, fontFamily: "Inter_600SemiBold", color: "#fff" },

  results: { borderTopWidth: 1, paddingTop: 16, gap: 14 },

  verdictBanner: { flexDirection: "row", alignItems: "flex-start", gap: 12, borderWidth: 1, padding: 14 },
  verdictLabel: { fontSize: 15, fontFamily: "Inter_700Bold", marginBottom: 3 },
  verdictSummary: { fontSize: 13, fontFamily: "Inter_400Regular", lineHeight: 19 },
  verdictPill: { flexDirection: "row", alignItems: "center", gap: 5, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 20 },
  verdictPillText: { fontSize: 11, fontFamily: "Inter_600SemiBold" },
  storedSummary: { fontSize: 13, fontFamily: "Inter_400Regular", lineHeight: 20 },
  graphWrap: { borderWidth: 1, padding: 12, overflow: "hidden" },

  subSection: { borderTopWidth: 1, paddingTop: 12, gap: 0 },
  subLabel: { fontSize: 11, fontFamily: "Inter_600SemiBold", textTransform: "uppercase", letterSpacing: 0.5, marginBottom: 8 },
  collapsibleRow: { flexDirection: "row", alignItems: "center", marginBottom: 8 },
  countPill: { paddingHorizontal: 7, paddingVertical: 2, borderRadius: 10 },
  countPillText: { fontSize: 11, fontFamily: "Inter_600SemiBold" },
  sectionPreview: { fontSize: 12, fontFamily: "Inter_400Regular", lineHeight: 18, marginBottom: 4, opacity: 0.8 },

  probeRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", borderTopWidth: 1, paddingVertical: 10 },
  probeName: { fontSize: 14, fontFamily: "Inter_600SemiBold" },
  probeRange: { fontSize: 12, fontFamily: "Inter_400Regular", marginTop: 2 },
  probeFinish: { fontSize: 22, fontFamily: "Inter_700Bold" },

  eventRow: { flexDirection: "row", alignItems: "flex-start", gap: 10, borderTopWidth: 1, paddingVertical: 10 },
  eventIconWrap: { width: 26, height: 26, borderRadius: 6, alignItems: "center", justifyContent: "center", marginTop: 1 },
  eventDesc: { fontSize: 13, fontFamily: "Inter_400Regular", lineHeight: 19 },
  eventTime: { fontSize: 12, fontFamily: "Inter_500Medium", paddingTop: 4 },

  bulletRow: { flexDirection: "row", alignItems: "flex-start", gap: 8, paddingBottom: 6 },
  bulletNum: { fontSize: 13, fontFamily: "Inter_700Bold", minWidth: 16 },
  bulletText: { flex: 1, fontSize: 13, fontFamily: "Inter_400Regular", lineHeight: 20 },

  noDataRow: { flexDirection: "row", alignItems: "flex-start", gap: 8 },
  noDataText: { flex: 1, fontSize: 13, fontFamily: "Inter_400Regular", lineHeight: 19 },

  phaseCard: { borderWidth: 1, padding: 14, gap: 10 },
  phaseChip: { flexDirection: "row", alignItems: "center", gap: 5, paddingHorizontal: 10, paddingVertical: 5, borderRadius: 20, borderWidth: 1 },
  phaseChipText: { fontSize: 12, fontFamily: "Inter_700Bold" },
  phaseNarrative: { fontSize: 14, fontFamily: "Inter_400Regular", lineHeight: 21 },
  phaseChips: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  timeChip: { flexDirection: "row", alignItems: "center", gap: 5, paddingHorizontal: 10, paddingVertical: 5, borderRadius: 20, borderWidth: 1 },
  timeChipText: { fontSize: 12, fontFamily: "Inter_600SemiBold" },

  decisionsSection: { gap: 10 },
  decisionCard: { borderWidth: 1, padding: 14, gap: 8 },
  decisionHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  decisionActionChip: { flexDirection: "row", alignItems: "center", gap: 6, paddingHorizontal: 10, paddingVertical: 5, borderRadius: 20, borderWidth: 1 },
  decisionActionText: { fontSize: 12, fontFamily: "Inter_700Bold" },
  decisionUrgencyBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6 },
  decisionUrgencyText: { fontSize: 10, fontFamily: "Inter_700Bold", color: "#fff", letterSpacing: 0.5 },
  decisionInstruction: { fontSize: 15, fontFamily: "Inter_600SemiBold", lineHeight: 22 },
  decisionRationale: { fontSize: 13, fontFamily: "Inter_400Regular", lineHeight: 20 },

  alertBtnRow: { borderTopWidth: 1, padding: 12, flexDirection: "row" },
  setAlertBtn: { flexDirection: "row", alignItems: "center", gap: 6, borderWidth: 1, paddingHorizontal: 14, paddingVertical: 8 },
  setAlertBtnText: { fontSize: 13, fontFamily: "Inter_600SemiBold" },
  alertCountBadge: { minWidth: 18, height: 18, borderRadius: 9, alignItems: "center", justifyContent: "center", paddingHorizontal: 4 },
  alertCountText: { fontSize: 11, fontFamily: "Inter_700Bold", color: "#fff" },
  alertSheet: { borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 20, gap: 16, maxHeight: "85%" },
  alertSheetHeader: { flexDirection: "row", alignItems: "center", gap: 10, borderBottomWidth: 1, paddingBottom: 14 },
  alertModeRow: { flexDirection: "row", padding: 3, gap: 2 },
  alertModeBtn: { flex: 1, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6, paddingVertical: 8 },
  alertModeBtnText: { fontSize: 13, fontFamily: "Inter_600SemiBold" },
  alertTimerOptions: { flexDirection: "row", gap: 8, marginBottom: 0 },
  alertTimerChip: { flex: 1, alignItems: "center", paddingVertical: 10, borderWidth: 1 },
  alertTimerChipText: { fontSize: 13, fontFamily: "Inter_600SemiBold" },
  alertWarning: { flexDirection: "row", alignItems: "flex-start", gap: 8, padding: 12, borderWidth: 1 },
  alertWarningText: { flex: 1, fontSize: 12, fontFamily: "Inter_400Regular", lineHeight: 18 },

  persistentDecisionBanner: {
    borderWidth: 1,
    borderRadius: 12,
    padding: 14,
    gap: 8,
  },
  persistentDecisionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  persistentUrgencyBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  persistentUrgencyText: {
    fontSize: 10,
    fontFamily: "Inter_700Bold",
    color: "#fff",
    letterSpacing: 0.6,
  },
  persistentDecisionLabel: {
    fontSize: 11,
    fontFamily: "Inter_400Regular",
    flex: 1,
  },
  persistentDecisionInstruction: {
    fontSize: 16,
    fontFamily: "Inter_700Bold",
    lineHeight: 23,
  },
  persistentDecisionRationale: {
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    lineHeight: 19,
  },

  keyTakeawayCard: {
    borderWidth: 1,
    borderRadius: 10,
    padding: 12,
    gap: 6,
  },
  keyTakeawayHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  keyTakeawayLabel: {
    fontSize: 11,
    fontFamily: "Inter_700Bold",
    letterSpacing: 0.4,
    textTransform: "uppercase",
  },
  keyTakeawayText: {
    fontSize: 14,
    fontFamily: "Inter_500Medium",
    lineHeight: 21,
  },

  historySection: { borderWidth: 1, padding: 16, gap: 0 },
  historyEntry: { paddingTop: 12, gap: 8 },
  historyEntryHeader: { flexDirection: "row", alignItems: "flex-start", gap: 10 },
  historyIndex: {
    width: 24, height: 24, borderRadius: 12,
    alignItems: "center", justifyContent: "center",
    flexShrink: 0,
  },
  historyIndexText: { fontSize: 11, fontFamily: "Inter_700Bold" },
  historyTimestamp: { fontSize: 13, fontFamily: "Inter_600SemiBold", marginBottom: 2 },
  historyMeta: { flexDirection: "row", gap: 8, flexWrap: "wrap" },
  historyMetaChip: { fontSize: 11, fontFamily: "Inter_400Regular" },
  historyVerdictBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6 },
  historyVerdictText: { fontSize: 11, fontFamily: "Inter_600SemiBold", textTransform: "capitalize" },
  historyDecision: {
    flexDirection: "row", alignItems: "flex-start", gap: 8,
    borderWidth: 1, borderRadius: 8, paddingHorizontal: 10, paddingVertical: 8,
  },
  historyDecisionDot: { width: 6, height: 6, borderRadius: 3, marginTop: 5, flexShrink: 0 },
  historyDecisionText: { fontSize: 13, fontFamily: "Inter_500Medium", flex: 1, lineHeight: 19 },
  historyPhase: { fontSize: 12, fontFamily: "Inter_400Regular" },
  historySummary: { fontSize: 12, fontFamily: "Inter_400Regular", lineHeight: 17 },
  historyNotes: { fontSize: 11, fontFamily: "Inter_400Regular", fontStyle: "italic" },

  metaRow: { flexDirection: "row", flexWrap: "wrap", gap: 10, borderTopWidth: 1, paddingTop: 10 },
  metaPill: { flexDirection: "row", alignItems: "center", gap: 5 },
  metaText: { fontSize: 12, fontFamily: "Inter_400Regular" },

  actionBtn: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 10, height: 52 },
  actionText: { fontSize: 16, fontFamily: "Inter_600SemiBold", color: "#fff" },
  homeLink: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6, paddingVertical: 8 },
  homeLinkText: { fontSize: 13, fontFamily: "Inter_400Regular" },

  editBtn: { padding: 4 },
  gradePrompt: { flexDirection: "row", alignItems: "flex-start", gap: 12, borderWidth: 1, padding: 14 },
  gradePromptTitle: { fontSize: 15, fontFamily: "Inter_700Bold", marginBottom: 3 },
  gradePromptSub: { fontSize: 13, fontFamily: "Inter_400Regular", lineHeight: 19 },

  editHeader: { flexDirection: "row", alignItems: "center", paddingHorizontal: 18, paddingBottom: 16, gap: 10 },
  editFireBar: { height: 2 },
  editCancelBtn: { minWidth: 60 },
  editCancelText: { fontSize: 15, fontFamily: "Inter_400Regular", color: "#F3EDE1", opacity: 0.8 },
  editHeaderTitle: { flex: 1, textAlign: "center", fontSize: 17, fontFamily: "Inter_700Bold", color: "#F3EDE1" },
  editSaveBtn: { minWidth: 60, alignItems: "flex-end" },
  editSaveText: { fontSize: 15, fontFamily: "Inter_700Bold", color: "#FF6B2B" },
  editFieldWrap: { gap: 6 },
  editLabel: { fontSize: 12, fontFamily: "Inter_600SemiBold", textTransform: "uppercase", letterSpacing: 0.3 },
  editInput: { borderWidth: 1, height: 44, paddingHorizontal: 12, fontSize: 14, fontFamily: "Inter_400Regular" },
  editPickerRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  editRow2: { flexDirection: "row", gap: 12 },
  editTextArea: { borderWidth: 1, padding: 12, fontSize: 14, fontFamily: "Inter_400Regular", minHeight: 100, lineHeight: 20 },
  nowBtn: { borderWidth: 1, height: 44, paddingHorizontal: 14, alignItems: "center", justifyContent: "center" },
  nowBtnText: { fontSize: 14, fontFamily: "Inter_600SemiBold" },
  editPickerBtn: { flexDirection: "row", alignItems: "center", gap: 7 },

  timerRow: { flexDirection: "row", gap: 10, padding: 14, borderTopWidth: 1 },
  timerChip: { flex: 1, flexDirection: "row", alignItems: "center", gap: 8, borderWidth: 1, borderRadius: 10, padding: 10 },
  timerValue: { fontSize: 17, fontFamily: "Inter_700Bold" },
  timerLabel: { fontSize: 10, fontFamily: "Inter_500Medium", marginTop: 1 },
  liveGraphWrap: { borderTopWidth: 1, padding: 14 },
  weatherStrip: { flexDirection: "row", alignItems: "center", gap: 7, borderTopWidth: 1, paddingHorizontal: 14, paddingVertical: 9 },
  weatherTemp: { fontSize: 13, fontFamily: "Inter_600SemiBold" },
  weatherCondition: { fontSize: 12, fontFamily: "Inter_400Regular" },
  weatherText: { fontSize: 12, fontFamily: "Inter_400Regular" },
  meaterPlaceholder: { borderTopWidth: 1, flexDirection: "row", alignItems: "center", gap: 10, padding: 16 },
  meaterPlaceholderText: { flex: 1, fontSize: 13, fontFamily: "Inter_400Regular", lineHeight: 19 },
  grillOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.5)" },
  grillSheet: { maxHeight: "65%", borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 20 },
  grillSheetHandle: { width: 36, height: 4, borderRadius: 2, alignSelf: "center", marginBottom: 16 },
  grillSheetTitle: { fontSize: 17, fontFamily: "Inter_700Bold", marginBottom: 12 },
  grillItem: { flexDirection: "row", alignItems: "center", paddingVertical: 14, borderBottomWidth: 1 },
  grillItemText: { fontSize: 15, fontFamily: "Inter_500Medium", flex: 1 },
  grillItemSub: { fontSize: 12, fontFamily: "Inter_400Regular", marginRight: 8 },
  grillEmpty: { fontSize: 14, fontFamily: "Inter_400Regular", textAlign: "center", paddingVertical: 20 },

  connectedBadgeSmall: { flexDirection: "row", alignItems: "center", gap: 5, borderRadius: 99, paddingHorizontal: 8, paddingVertical: 5 },
  liveIndicator: { width: 7, height: 7, borderRadius: 99 },
  liveText: { fontSize: 11, fontFamily: "Inter_700Bold", letterSpacing: 0.5 },
  meaterTempsRow: { flexDirection: "row", gap: 10, flexWrap: "wrap" },
  meaterTempChip: { flexDirection: "row", alignItems: "center", gap: 8, flex: 1, minWidth: 90 },
  meaterTempValue: { fontSize: 18, fontFamily: "Inter_700Bold" },
  meaterTempLabel: { fontSize: 11, fontFamily: "Inter_400Regular", marginTop: 1 },
  meaterAutoFillBadge: { flexDirection: "row", alignItems: "center", gap: 6, borderRadius: 8, paddingHorizontal: 10, paddingVertical: 6, marginTop: 8 },
  meaterAutoFillText: { fontSize: 12, fontFamily: "Inter_500Medium", flex: 1 },

  ratingsSummary: { flexDirection: "row", alignItems: "center", gap: 10, marginLeft: "auto" },
  ratingsSummaryChip: { flexDirection: "row", alignItems: "center", gap: 4 },
  ratingsSummaryLabel: { fontSize: 10, fontFamily: "Inter_700Bold", letterSpacing: 0.3 },
  ratingsSummaryStars: { fontSize: 11, letterSpacing: -1 },

  rateRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 16, paddingVertical: 13, borderTopWidth: 1 },
  rateRowLeft: { flexDirection: "row", alignItems: "center", gap: 8 },
  rateRowLabel: { fontSize: 14, fontFamily: "Inter_500Medium" },
  starsRow: { flexDirection: "row", gap: 6 },
  star: { fontSize: 28, lineHeight: 32 },

  seqScheduleHeader: {
    flexDirection: "row", alignItems: "center", gap: 10,
    paddingHorizontal: 14, paddingVertical: 13,
  },
  seqScheduleIcon: {
    width: 30, height: 30, borderRadius: 8,
    alignItems: "center", justifyContent: "center",
  },
  seqScheduleTitle: { fontSize: 14, fontFamily: "Inter_700Bold" },
  seqScheduleSub: { fontSize: 11, fontFamily: "Inter_400Regular", marginTop: 1 },
  seqScheduleItem: {
    borderWidth: 1, borderRadius: 10, padding: 10,
  },
  seqScheduleItemHeader: {
    flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 10,
  },
  seqScheduleItemIcon: {
    width: 24, height: 24, borderRadius: 6,
    alignItems: "center", justifyContent: "center",
  },
  seqScheduleItemTitle: { fontSize: 13, fontFamily: "Inter_700Bold", flex: 1 },
  seqScheduleCurrentBadge: {
    backgroundColor: "#6C3BF520", borderRadius: 5,
    paddingHorizontal: 6, paddingVertical: 2,
  },
  seqScheduleCurrentText: {
    fontSize: 9, fontFamily: "Inter_700Bold", color: "#6C3BF5", letterSpacing: 0.5,
  },
  seqTlRow: {
    flexDirection: "row", alignItems: "flex-start", gap: 10, marginBottom: 8,
  },
  seqTlNextRow: {
    backgroundColor: "transparent",
    borderRadius: 8,
    paddingHorizontal: 6, paddingVertical: 4,
    marginHorizontal: -6,
  },
  seqTlLabelRow: {
    flexDirection: "row", alignItems: "center", gap: 5, marginBottom: 1,
  },
  seqTlNextBadge: {
    borderRadius: 4, paddingHorizontal: 5, paddingVertical: 1,
  },
  seqTlNextText: {
    fontSize: 8, fontFamily: "Inter_700Bold", letterSpacing: 0.5,
  },
  seqTlDot: {
    width: 10, height: 10, borderRadius: 5, marginTop: 4, flexShrink: 0,
  },
  seqTlDotBtn: {
    width: 14, height: 14, marginTop: 2, flexShrink: 0, alignItems: "center", justifyContent: "center",
  },
  seqTlConnector: {
    width: 1, backgroundColor: "transparent",
    borderLeftWidth: 1, borderColor: "#3f3f46", borderStyle: "dashed",
    position: "absolute", left: 8, top: 14, bottom: -8,
  },
  seqTlLabel: {
    fontSize: 10, fontFamily: "Inter_600SemiBold",
    textTransform: "uppercase", letterSpacing: 0.5,
  },
  seqTlDoneRow: {
    opacity: 0.6,
  },
  seqTlDoneLabel: {
    textDecorationLine: "line-through",
  },
  seqTlTime: { fontSize: 14, fontFamily: "Inter_700Bold" },
  seqTlMeta: { fontSize: 11, fontFamily: "Inter_400Regular" },
  seqTlNoteBox: {
    flexDirection: "row", alignItems: "flex-start", gap: 6,
    borderRadius: 7, padding: 8, marginTop: 8,
  },
  seqTlNoteText: { fontSize: 12, fontFamily: "Inter_400Regular", flex: 1, lineHeight: 17 },

});

export const edt = StyleSheet.create({
  overlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.5)", justifyContent: "flex-end" },
  sheet: { borderTopLeftRadius: 20, borderTopRightRadius: 20, paddingTop: 10, maxHeight: "70%" },
  handle: { width: 40, height: 4, borderRadius: 2, alignSelf: "center", marginBottom: 10 },
  header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 16, paddingBottom: 12, borderBottomWidth: 1 },
  title: { fontSize: 17, fontFamily: "Inter_700Bold" },
  row: { flexDirection: "row", alignItems: "center", paddingHorizontal: 4, paddingVertical: 14, gap: 10 },
  rowMain: { flex: 1, fontSize: 15, fontFamily: "Inter_600SemiBold" },
  rowSub: { fontSize: 12, fontFamily: "Inter_400Regular" },
});
